version: '3'

services:
  content:
    image: ghcr.io/ghosts-network/content:latest
    ports:
      - "5300:80"
    depends_on:
      - db
      - profiles
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/ghost-network
      - ASPNETCORE_ENVIRONMENT=Development
      - PROFILES_ADDRESS=http://profiles

  profiles:
    image: ghcr.io/ghosts-network/profiles:latest
    ports:
      - "5400:80"
    depends_on:
      - db
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/ghost-network
      - ASPNETCORE_ENVIRONMENT=Development

  s3:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"

  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
