/* 
 * GhostNetwork/Publications API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GhostNetwork.Publications.Client.OpenAPIDateConverter;

namespace GhostNetwork.Publications.Model
{
    /// <summary>
    /// Defines Ordering
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Ordering
    {
        /// <summary>
        /// Enum Asc for value: Asc
        /// </summary>
        [EnumMember(Value = "Asc")]
        Asc = 1,

        /// <summary>
        /// Enum Desc for value: Desc
        /// </summary>
        [EnumMember(Value = "Desc")]
        Desc = 2

    }

}
