/* 
 * Reactions
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using GhostNetwork.Reactions.Client;
using GhostNetwork.Reactions.Model;

namespace GhostNetwork.Reactions.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReactionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Dictionary&lt;string, int&gt;</returns>
        Dictionary<string, int> ReactionsKeyDelete (string key, string author = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, int&gt;</returns>
        ApiResponse<Dictionary<string, int>> ReactionsKeyDeleteWithHttpInfo (string key, string author = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <returns>Dictionary&lt;string, int&gt;</returns>
        Dictionary<string, int> ReactionsKeyGet (string key);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <returns>ApiResponse of Dictionary&lt;string, int&gt;</returns>
        ApiResponse<Dictionary<string, int>> ReactionsKeyGetWithHttpInfo (string key);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Dictionary&lt;string, int&gt;</returns>
        Dictionary<string, int> ReactionsKeyTypePost (string key, string type, string author = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, int&gt;</returns>
        ApiResponse<Dictionary<string, int>> ReactionsKeyTypePostWithHttpInfo (string key, string type, string author = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Dictionary&lt;string, int&gt;</returns>
        Dictionary<string, int> ReactionsKeyTypePut (string key, string type, string author = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, int&gt;</returns>
        ApiResponse<Dictionary<string, int>> ReactionsKeyTypePutWithHttpInfo (string key, string type, string author = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReactionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of Dictionary&lt;string, int&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, int>> ReactionsKeyDeleteAsync (string key, string author = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, int&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, int>>> ReactionsKeyDeleteAsyncWithHttpInfo (string key, string author = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <returns>Task of Dictionary&lt;string, int&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, int>> ReactionsKeyGetAsync (string key);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, int&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, int>>> ReactionsKeyGetAsyncWithHttpInfo (string key);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of Dictionary&lt;string, int&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, int>> ReactionsKeyTypePostAsync (string key, string type, string author = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, int&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, int>>> ReactionsKeyTypePostAsyncWithHttpInfo (string key, string type, string author = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of Dictionary&lt;string, int&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, int>> ReactionsKeyTypePutAsync (string key, string type, string author = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, int&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, int>>> ReactionsKeyTypePutAsyncWithHttpInfo (string key, string type, string author = default(string));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReactionsApi : IReactionsApiSync, IReactionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ReactionsApi : IReactionsApi
    {
        private GhostNetwork.Reactions.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReactionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReactionsApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReactionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReactionsApi(String basePath)
        {
            this.Configuration = GhostNetwork.Reactions.Client.Configuration.MergeConfigurations(
                GhostNetwork.Reactions.Client.GlobalConfiguration.Instance,
                new GhostNetwork.Reactions.Client.Configuration { BasePath = basePath }
            );
            this.Client = new GhostNetwork.Reactions.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GhostNetwork.Reactions.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = GhostNetwork.Reactions.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReactionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ReactionsApi(GhostNetwork.Reactions.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = GhostNetwork.Reactions.Client.Configuration.MergeConfigurations(
                GhostNetwork.Reactions.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new GhostNetwork.Reactions.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GhostNetwork.Reactions.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = GhostNetwork.Reactions.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReactionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ReactionsApi(GhostNetwork.Reactions.Client.ISynchronousClient client,GhostNetwork.Reactions.Client.IAsynchronousClient asyncClient, GhostNetwork.Reactions.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = GhostNetwork.Reactions.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public GhostNetwork.Reactions.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public GhostNetwork.Reactions.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public GhostNetwork.Reactions.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public GhostNetwork.Reactions.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Dictionary&lt;string, int&gt;</returns>
        public Dictionary<string, int> ReactionsKeyDelete (string key, string author = default(string))
        {
             GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>> localVarResponse = ReactionsKeyDeleteWithHttpInfo(key, author);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, int&gt;</returns>
        public GhostNetwork.Reactions.Client.ApiResponse< Dictionary<string, int> > ReactionsKeyDeleteWithHttpInfo (string key, string author = default(string))
        {
            // verify the required parameter 'key' is set
            if (key == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'key' when calling ReactionsApi->ReactionsKeyDelete");

            GhostNetwork.Reactions.Client.RequestOptions localVarRequestOptions = new GhostNetwork.Reactions.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = GhostNetwork.Reactions.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GhostNetwork.Reactions.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("key", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(key)); // path parameter
            if (author != null)
            {
                localVarRequestOptions.HeaderParameters.Add("author", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(author)); // header parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Delete< Dictionary<string, int> >("/Reactions/{key}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReactionsKeyDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of Dictionary&lt;string, int&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, int>> ReactionsKeyDeleteAsync (string key, string author = default(string))
        {
             GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>> localVarResponse = await ReactionsKeyDeleteAsyncWithHttpInfo(key, author);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, int&gt;)</returns>
        public async System.Threading.Tasks.Task<GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>>> ReactionsKeyDeleteAsyncWithHttpInfo (string key, string author = default(string))
        {
            // verify the required parameter 'key' is set
            if (key == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'key' when calling ReactionsApi->ReactionsKeyDelete");


            GhostNetwork.Reactions.Client.RequestOptions localVarRequestOptions = new GhostNetwork.Reactions.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("key", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(key)); // path parameter
            if (author != null)
            {
                localVarRequestOptions.HeaderParameters.Add("author", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(author)); // header parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Dictionary<string, int>>("/Reactions/{key}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReactionsKeyDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <returns>Dictionary&lt;string, int&gt;</returns>
        public Dictionary<string, int> ReactionsKeyGet (string key)
        {
             GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>> localVarResponse = ReactionsKeyGetWithHttpInfo(key);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <returns>ApiResponse of Dictionary&lt;string, int&gt;</returns>
        public GhostNetwork.Reactions.Client.ApiResponse< Dictionary<string, int> > ReactionsKeyGetWithHttpInfo (string key)
        {
            // verify the required parameter 'key' is set
            if (key == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'key' when calling ReactionsApi->ReactionsKeyGet");

            GhostNetwork.Reactions.Client.RequestOptions localVarRequestOptions = new GhostNetwork.Reactions.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = GhostNetwork.Reactions.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GhostNetwork.Reactions.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("key", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(key)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get< Dictionary<string, int> >("/Reactions/{key}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReactionsKeyGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <returns>Task of Dictionary&lt;string, int&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, int>> ReactionsKeyGetAsync (string key)
        {
             GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>> localVarResponse = await ReactionsKeyGetAsyncWithHttpInfo(key);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, int&gt;)</returns>
        public async System.Threading.Tasks.Task<GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>>> ReactionsKeyGetAsyncWithHttpInfo (string key)
        {
            // verify the required parameter 'key' is set
            if (key == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'key' when calling ReactionsApi->ReactionsKeyGet");


            GhostNetwork.Reactions.Client.RequestOptions localVarRequestOptions = new GhostNetwork.Reactions.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("key", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(key)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Dictionary<string, int>>("/Reactions/{key}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReactionsKeyGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Dictionary&lt;string, int&gt;</returns>
        public Dictionary<string, int> ReactionsKeyTypePost (string key, string type, string author = default(string))
        {
             GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>> localVarResponse = ReactionsKeyTypePostWithHttpInfo(key, type, author);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, int&gt;</returns>
        public GhostNetwork.Reactions.Client.ApiResponse< Dictionary<string, int> > ReactionsKeyTypePostWithHttpInfo (string key, string type, string author = default(string))
        {
            // verify the required parameter 'key' is set
            if (key == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'key' when calling ReactionsApi->ReactionsKeyTypePost");

            // verify the required parameter 'type' is set
            if (type == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'type' when calling ReactionsApi->ReactionsKeyTypePost");

            GhostNetwork.Reactions.Client.RequestOptions localVarRequestOptions = new GhostNetwork.Reactions.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = GhostNetwork.Reactions.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GhostNetwork.Reactions.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("key", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(key)); // path parameter
            localVarRequestOptions.PathParameters.Add("type", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(type)); // path parameter
            if (author != null)
            {
                localVarRequestOptions.HeaderParameters.Add("author", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(author)); // header parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Post< Dictionary<string, int> >("/Reactions/{key}/{type}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReactionsKeyTypePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of Dictionary&lt;string, int&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, int>> ReactionsKeyTypePostAsync (string key, string type, string author = default(string))
        {
             GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>> localVarResponse = await ReactionsKeyTypePostAsyncWithHttpInfo(key, type, author);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, int&gt;)</returns>
        public async System.Threading.Tasks.Task<GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>>> ReactionsKeyTypePostAsyncWithHttpInfo (string key, string type, string author = default(string))
        {
            // verify the required parameter 'key' is set
            if (key == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'key' when calling ReactionsApi->ReactionsKeyTypePost");

            // verify the required parameter 'type' is set
            if (type == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'type' when calling ReactionsApi->ReactionsKeyTypePost");


            GhostNetwork.Reactions.Client.RequestOptions localVarRequestOptions = new GhostNetwork.Reactions.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("key", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(key)); // path parameter
            localVarRequestOptions.PathParameters.Add("type", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(type)); // path parameter
            if (author != null)
            {
                localVarRequestOptions.HeaderParameters.Add("author", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(author)); // header parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Dictionary<string, int>>("/Reactions/{key}/{type}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReactionsKeyTypePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Dictionary&lt;string, int&gt;</returns>
        public Dictionary<string, int> ReactionsKeyTypePut (string key, string type, string author = default(string))
        {
             GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>> localVarResponse = ReactionsKeyTypePutWithHttpInfo(key, type, author);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, int&gt;</returns>
        public GhostNetwork.Reactions.Client.ApiResponse< Dictionary<string, int> > ReactionsKeyTypePutWithHttpInfo (string key, string type, string author = default(string))
        {
            // verify the required parameter 'key' is set
            if (key == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'key' when calling ReactionsApi->ReactionsKeyTypePut");

            // verify the required parameter 'type' is set
            if (type == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'type' when calling ReactionsApi->ReactionsKeyTypePut");

            GhostNetwork.Reactions.Client.RequestOptions localVarRequestOptions = new GhostNetwork.Reactions.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = GhostNetwork.Reactions.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GhostNetwork.Reactions.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("key", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(key)); // path parameter
            localVarRequestOptions.PathParameters.Add("type", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(type)); // path parameter
            if (author != null)
            {
                localVarRequestOptions.HeaderParameters.Add("author", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(author)); // header parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Put< Dictionary<string, int> >("/Reactions/{key}/{type}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReactionsKeyTypePut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of Dictionary&lt;string, int&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, int>> ReactionsKeyTypePutAsync (string key, string type, string author = default(string))
        {
             GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>> localVarResponse = await ReactionsKeyTypePutAsyncWithHttpInfo(key, type, author);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="GhostNetwork.Reactions.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key"></param>
        /// <param name="type"></param>
        /// <param name="author"> (optional)</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, int&gt;)</returns>
        public async System.Threading.Tasks.Task<GhostNetwork.Reactions.Client.ApiResponse<Dictionary<string, int>>> ReactionsKeyTypePutAsyncWithHttpInfo (string key, string type, string author = default(string))
        {
            // verify the required parameter 'key' is set
            if (key == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'key' when calling ReactionsApi->ReactionsKeyTypePut");

            // verify the required parameter 'type' is set
            if (type == null)
                throw new GhostNetwork.Reactions.Client.ApiException(400, "Missing required parameter 'type' when calling ReactionsApi->ReactionsKeyTypePut");


            GhostNetwork.Reactions.Client.RequestOptions localVarRequestOptions = new GhostNetwork.Reactions.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("key", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(key)); // path parameter
            localVarRequestOptions.PathParameters.Add("type", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(type)); // path parameter
            if (author != null)
            {
                localVarRequestOptions.HeaderParameters.Add("author", GhostNetwork.Reactions.Client.ClientUtils.ParameterToString(author)); // header parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Dictionary<string, int>>("/Reactions/{key}/{type}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReactionsKeyTypePut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
